apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: null
  name: pacman-hpa
spec:
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 20
  maxReplicas: 5
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pacman
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 10
status:
  currentReplicas: 3
  desiredReplicas: 3
